<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>eBuildingBlocks Application</Title>
    <Authors>Inam Ul Haq</Authors>
    <Company>https://www.linkedin.com/in/inam1567/</Company>
    <Product>eBuildingBlocks Application</Product>
    <Description>Reusable building block for the  ecosystem. Implements core cross-cutting concerns, infrastructure, or domain utilities for .NET applications.</Description>
    <Copyright>Copyright © linkedin/in/inam1567. All rights reserved.</Copyright>
    <RepositoryUrl>https://github.com/ghazi1567/eBuildingBlocks</RepositoryUrl>
    <Version>2.0.7</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.1.1" />
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
		<PackageReference Include="Humanizer.Core" Version="3.0.10" />
		<PackageReference Include="MediatR" Version="14.1.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
		<PackageReference Include="Polly" Version="8.6.6" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
		<PackageReference Include="Microsoft.FeatureManagement" Version="4.4.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\eBuildingBlocks.Common\eBuildingBlocks.Common.csproj" />
		<ProjectReference Include="..\eBuildingBlocks.Domain\eBuildingBlocks.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

</Project>
