name: Publish NuGet Packages

on:
  push:
    tags:
      - 'v*.*.*' # Trigger only on version tags, e.g. v1.2.3

jobs:
  pack-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # or your required version

      - name: Restore dependencies
        run: dotnet restore

      - name: Pack all projects
        run: |
          for proj in $(find ./eBuildingBlocks -name '*.csproj'); do
            dotnet pack "$proj" --configuration Release --output ./nupkgs
          done

      - name: Publish to NuGet.org
        run: |
          for pkg in ./nupkgs/*.nupkg; do
            dotnet nuget push "$pkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          done
