name: Publish NuGet Packages

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # or your required version

      - name: Restore dependencies
        run: dotnet restore eBuildingBlocks.sln

      - name: Build all projects (creates .nupkg in bin/Release)
        run: dotnet build eBuildingBlocks.sln --configuration Release

      - name: Publish all .nupkg files from bin/Release to NuGet.org
        run: |
          find ./eBuildingBlocks -type f -name '*.nupkg' -path '*/bin/Release/*' | while read pkg; do
            dotnet nuget push "$pkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          done
